### ISSUE TITLE
Requires Kotlin

### ISSUE THREAD

**Issue by BalancedOneshot** [RedCarlos26/HIGTools#1]
- Mod 'HIG Tools' (hig-tools) 1.6 requires version 1.8.0+kotlin.1.7.0 or later of fabric-language-kotlin, which is missing!

This addon requires an extra mod to work.
https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin/files

**Comment by RedCarlos26** [comment]
I am aware. I think I've put it in the dependencies in the code.

**Comment by RedCarlos26** [comment]
This is intended, I don't see why you say it's an issue. Some of the client is in kotlin.
