### ISSUE TITLE
Minecraft crashes after enabling highway-builder+ module

### ISSUE THREAD

**Issue by Nxtyrs** [RedCarlos26/HIGTools#18]
[crash-2023-09-06_19.01.56-client.txt](https://github.com/RedCarlos26/HIGTools/files/12542901/crash-2023-09-06_19.01.56-client.txt)

**Comment by Nxtyrs** [comment]
it also happens with highway-tools
[crash-2023-09-06_19.35.34-client.txt](https://github.com/RedCarlos26/HIGTools/files/12543039/crash-2023-09-06_19.35.34-client.txt)

**Comment by RedCarlos26** [comment]
@Nxtyrs try turning off auto tool before and send the crash report if it still crashes please

**Comment by Nxtyrs** [comment]
here it is @RedCarlos26 
[crash-2023-09-07_19.45.51-client.txt](https://github.com/RedCarlos26/HIGTools/files/12553953/crash-2023-09-07_19.45.51-client.txt)

**Comment by RedCarlos26** [comment]
Alright thanks! I will take a look at that

**Comment by RedCarlos26** [comment]
Fixed in 5fa02c79614427c4779a188450bec13de1830ff4
