### ISSUE TITLE
[Suggestion] Some suggestions for new features

### ISSUE THREAD

**Issue by MeowStarrySea** [RedCarlos26/HIGTools#19]
If possible, I hope to add these features
1. Stop HighwayBuilder when a certain number of EnderChests remain . The golden apple and the pickaxe are the same and they can adjust how much to keep and whether to keep
2. At present, I don't see any function to detect and take items from inventory\Shulker Box\EnderChest. I hope it can be added and I think its order is to check whether any Shulker Box contains the items I need from inventory If it doesn't, you check if it's in your EnderChest and if it's there, you take it
3. I expect the detailed parameters for mining and placement to be modifiable
4. I would like to have a feature that automatically detects magma and fills in the same way that the placement and detection of this feature is highly customizable
PS: My mother tongue is not English, so I am using a translator to communicate. If you can't understand anything, please reply to me and I will explain it to you

**Comment by RedCarlos26** [comment]
Hi! I appreciate your time for suggesting all of those things! I can assure you I already thought about that, the unfortunate thing is that those features are way more complex than what I'm currently able to code (I am still a rookie). If I can get some help from someone else then obviously yes, I would implement that!

**Comment by MeowStarrySea** [comment]
> Hi! I appreciate your time for suggesting all of those things! I can assure you I already thought about that, the unfortunate thing is that those features are way more complex than what I'm currently able to code (I am still a rookie). If I can get some help from someone else then obviously yes, I would implement that!你好！我感谢您花时间提出所有这些建议！我可以向你保证，我已经考虑过这一点，不幸的是，这些功能比我目前能够编写的功能要复杂得多（我仍然是菜鸟）。如果我可以从其他人那里得到一些帮助，那么显然是的，我会实现它！

I don't know anything about code, so I can't help you. But if there's something like testing I might be able to help you with that. Thank you for your consideration of my proposal

**Comment by MeowStarrySea** [comment]
reopen?

**Comment by RedCarlos26** [comment]
Yes, I will try to work on this eventually!

**Comment by RedCarlos26** [comment]
@MeowStarrySea go check this out ;) https://discord.com/channels/1016546120119369848/1016549436656205855/1263627438802600076
