### ISSUE TITLE
[Bug] Issues with hig on 8b8t.me

### ISSUE THREAD

**Issue by minecrafterxx2** [RedCarlos26/HIGTools#20]
theres a issue with 8b bc hig tools goes maybe too fast for anticheat or idk but sometimes it leaves holes in the floor

**Comment by RedCarlos26** [comment]
Can you give more information on how this is happening please?

**Comment by minecrafterxx2** [comment]
hig sometimes doesnt place obi and makes holes maybe anticheat issue maybe the addon and its annoying

**Comment by RedCarlos26** [comment]
Do you have rotate enabled for block placements?

**Comment by RedCarlos26** [comment]
Can you try with this release : https://github.com/RedCarlos26/HIGTools/commit/cdf574d230c3ffc13dac93eb3382b6c25cd061bb

And place delay 4?
