### ISSUE TITLE
[bug] Highway Builder+ keeps stopping

### ISSUE THREAD

**Issue by zhubenjamin** [RedCarlos26/HIGTools#21]
It randomly stops. Every time it does this, there's obbsidian in the middle of the inv gui. It might be Hotbar Manager and Highway Builder+ trying to grab it at the same time. The moment I put the obsidian in the hotbar, it continues.

**Comment by zhubenjamin** [comment]
Update: I disabled Hand Manager and the issue continued. It seems that every time it grabs the obsidian right before it tosses all the netherrack out and starts mining enderchests

**Comment by RedCarlos26** [comment]
Yea that's exactly the issue atm...

**Comment by RedCarlos26** [comment]
Fixed in https://github.com/RedCarlos26/HIGTools/commit/cdf574d230c3ffc13dac93eb3382b6c25cd061bb
