### ISSUE TITLE
[suggestion] Scaffold+ whitelist/blacklist blocks

### ISSUE THREAD

**Issue by zhubenjamin** [RedCarlos26/HIGTools#22]
I need this because Scaffold+ keeps placing things like enderchests (put in hotbar by Highway Builder+/Hotbar manager), which cause problems as they are 1 pixel lower than normal blocks, and they are openable.

**Comment by RedCarlos26** [comment]
Will work on this when I have time to. For the time being, just don`t put those blocks in your hotbar.

**Comment by RedCarlos26** [comment]
Will get added in 2.9.0
