### ISSUE TITLE
[bug] Highway Builder+ randomly goes down one block

### ISSUE THREAD

**Issue by zhubenjamin** [RedCarlos26/HIGTools#23]
Highway Builder+ randomly goes down from y=120 to y=119. No idea why. I have velocity enabled and a gold peice on (I'm in the nether)

Server: anarchy.8b8t.me
OS: Windows 10 (tested on Home and Pro)
Version: HIGTools 2.7.1 + Meteor 0.5.6-2005 + MC Fabric 1.20.4

**Comment by RedCarlos26** [comment]
Fixed in newest release
