### ISSUE TITLE
None of the versions for 1.20.4 work!

### ISSUE THREAD

**Issue by K-K-L-L** [RedCarlos26/HIGTools#29]
The title says it all, some versions are labeled "version 1.20.4" but they are really for version 1.21, I did get the first release of the 1.20.4 version though, but it crashed my game when I enabled the HighwayBuilder+ module.

This addon is such a big scam, why is it even in [AntiCope](https://anticope.pages.dev/addons/?)? I don't get the purpose of "maintaining" an addon when it doesn't work at all, please fix your addon!

**Comment by Big-Iron-Cheems** [comment]
[This](https://github.com/RedCarlos26/HIGTools/releases/tag/2.9.0-1.20.4) version is clearly marked as 1.20.4 and runs if you use Meteor 1.20.4 with it.
Tested on PrismLauncher with Meteor 0.5.6 as required, obviously on Minecraft 1.20.4.

A lot of entitlement from someone that probably has never written a piece of original software with more than one file.

**Comment by RickyTheRacc** [comment]
Awful long way of saying cope :3
