### ISSUE TITLE
auto center 無法關閉

### ISSUE THREAD

**Issue by Top4nk-777** [RedCarlos26/HIGTools#32]
我將Highwal tools和auto center的快捷鍵設為right alt,當我打開時被服務器踢出了
再次進入後,auto center看著是關閉狀態,實際是開啟,無法轉動視角,也無法關閉他

**Comment by RedCarlos26** [comment]
What?

**Comment by RedCarlos26** [comment]
不幸的是，這是一個流星客戶端的錯誤。 我對此無能為力......
